// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	user3 "github.com/backent/go-article/controllers/user"
	"github.com/backent/go-article/libs"
	"github.com/backent/go-article/repositories/user"
	user2 "github.com/backent/go-article/services/user"
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
)

// Injectors from injector.go:

func InitializeRouter() *httprouter.Router {
	db := libs.Initiate()
	repositoryUserInterface := user.NewRepositoryMysqlImpl()
	validate := libs.NewValidator()
	serviceUserInterface := user2.NewServiceUser(db, repositoryUserInterface, validate)
	controllerUserInterface := user3.NewControllerUser(serviceUserInterface)
	router := libs.NewRouter(controllerUserInterface)
	return router
}

// injector.go:

var userSet = wire.NewSet(user.NewRepositoryMysqlImpl, user2.NewServiceUser, user3.NewControllerUser)
